version: '3.8'

services:
  phishing-detector-api:
    image: polaadolf/phishing-detector-api:latest
    build: .
    container_name: phishing_detector_api
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./models:/app/models
    restart: always
